import os
import re
import json

projects_dir = r"c:\Users\panka\Downloads\Resume\Projects"
js_output_path = r"c:\Users\panka\Downloads\Resume\projects_data.js"

# Get all project folders
folders = [f for f in os.listdir(projects_dir) if os.path.isdir(os.path.join(projects_dir, f)) and re.match(r'^\d+_', f)]
# Sort by the number prefix
folders.sort(key=lambda x: int(x.split('_')[0]))

projects_data = []

for index, folder in enumerate(folders):
    base_path = os.path.join(projects_dir, folder)
    
    # Read files
    try:
        with open(os.path.join(base_path, 'Name.txt'), 'r', encoding='utf-8') as f:
            name = f.read().strip()
    except FileNotFoundError:
        name = folder.split('_', 1)[1].replace('_', ' ')
        
    try:
        with open(os.path.join(base_path, 'Description.txt'), 'r', encoding='utf-8') as f:
            description = f.read().strip()
    except FileNotFoundError:
        description = ""
        
    try:
        with open(os.path.join(base_path, 'Tech.txt'), 'r', encoding='utf-8') as f:
            tech_lines = [line.strip() for line in f.readlines() if line.strip()]
    except FileNotFoundError:
        tech_lines = []
        
    try:
        with open(os.path.join(base_path, 'Url.txt'), 'r', encoding='utf-8') as f:
            urls = [line.strip() for line in f.readlines() if line.strip()]
    except FileNotFoundError:
        urls = []
        
    try:
        with open(os.path.join(base_path, 'Role.txt'), 'r', encoding='utf-8') as f:
            role_lines = [line.strip().lstrip('- ') for line in f.readlines() if line.strip()]
    except FileNotFoundError:
        role_lines = []
        
    media = []
    media_dir = os.path.join(base_path, 'Media')
    if os.path.exists(media_dir):
        media_files = os.listdir(media_dir)
        for m in media_files:
            file_type = ""
            m_lower = m.lower()
            if m_lower.endswith(('.mp4', '.webm', '.ogg', '.mov', '.avi', '.mkv', '.m4v', '.mp3', '.wav')):
                file_type = "video"
            elif m_lower.endswith(('.jpg', '.png', '.jpeg', '.webp', '.gif', '.bmp', '.svg', '.tiff', '.ico')):
                file_type = "image"
            elif m_lower.endswith('.txt'):
                try:
                    with open(os.path.join(media_dir, m), 'r', encoding='utf-8') as f:
                        url = f.read().strip()
                        if url:
                            # Simple URL type detection
                            low_url = url.lower()
                            if 'youtube.com' in low_url or 'youtu.be' in low_url:
                                # Keep the original YouTube link for the best watch experience on the platform
                                pass
                            elif 'drive.google.com' in low_url:
                                # Keep the original Drive link as it provides a better player experience than direct download links
                                pass
                                
                                # We'll assume it's an image unless it has a video extension in the name (rare for drive links)
                                file_type = "image"
                                if any(ext in low_url for ext in ['.mp4', '.webm', '.mov']):
                                    file_type = "video"
                            elif any(ext in low_url for ext in ['.mp4', '.webm', '.ogg', '.mov', '.avi']):
                                file_type = "video"
                            elif any(ext in low_url for ext in ['.jpg', '.png', '.jpeg', '.webp', '.gif']):
                                file_type = "image"
                            else:
                                # Fallback to iframe for unknown sites like Instagram
                                file_type = "youtube" # We use the youtube (iframe) handler for general embeds
                            
                            media.append({
                                "path": url,
                                "type": file_type,
                                "isExternal": True
                            })
                            continue # Skip the normal path appending
                except Exception:
                    pass
            
            if file_type:
                media.append({
                    "path": f"Projects/{folder}/Media/{m}",
                    "type": file_type
                })

    projects_data.append({
        "name": name,
        "description": description,
        "tech": tech_lines,
        "urls": urls,
        "role": role_lines,
        "media": media
    })

# Write to JS file
with open(js_output_path, 'w', encoding='utf-8') as f:
    f.write("// This file is automatically generated by build_projects.py\n")
    f.write("const projectsData = ")
    json.dump(projects_data, f, indent=4)
    f.write(";")

print(f"Successfully generated {js_output_path} with {len(projects_data)} projects.")
