// This file is automatically generated by build_projects.py
const projectsData = [
    {
        "name": "Raptor Flight",
        "description": "Interactive aviation map and cabin experience platform designed for premium onboard entertainment systems.\n\nThe application provides high-quality 3D map visualization, flight-related geographic content, points of interest, and interactive location-based experiences optimized for onboard systems and connected displays.\n\nFeatures may include:\n\nReal-time and interactive 3D map rendering, \nGlobal terrain and geographic visualization, \nCity and landmark information, \nPoints of interest and informational content, \nOptimized performance for embedded and aviation-related environments and\nModern touch-friendly user interface.\n\nThe application is designed for specialized deployments and integrated entertainment solutions.",
        "tech": [
            "Unity",
            "C#",
            "Animation",
            "UI",
            "Cesium For Unity",
            "Animations",
            "DoTween"
        ],
        "urls": [
            "https://apps.apple.com/us/app/raptor-flight/id6755526667"
        ],
        "role": [
            "End to end Frontend and UI",
            "Designed and implemented the path logic, API and socket connections, 3D Terrains, Localizations, Map Layers and Auto Play, Configs, etc."
        ],
        "media": [
            {
                "path": "Projects/1_Raptor_Flight/Media/1.webp",
                "type": "image"
            },
            {
                "path": "Projects/1_Raptor_Flight/Media/2.webp",
                "type": "image"
            },
            {
                "path": "Projects/1_Raptor_Flight/Media/3.webp",
                "type": "image"
            },
            {
                "path": "Projects/1_Raptor_Flight/Media/4.webp",
                "type": "image"
            }
        ]
    },
    {
        "name": "Cuddle Cubbies",
        "description": "Cuddle Cubbies is a fast-paced endless runner game inspired by classics like Subway Surfers. Players navigate dynamic, infinitely generating paths while dodging obstacles and collecting power-ups to achieve the highest score possible.",
        "tech": [
            "Unity",
            "C#",
            "Animation",
            "IAP",
            "Google Ads",
            "Firebase"
        ],
        "urls": [
            "https://play.google.com/store/apps/details?id=com.CuddleCubbies.EndlessRunner&hl=en_IN"
        ],
        "role": [
            "Engineered the core endless runner mechanics and obstacle generation systems.",
            "Designed and implemented the complete UI setup for menus and gameplay overlays.",
            "Built robust data handlers integrating Firebase for analytics and cloud save functionality."
        ],
        "media": [
            {
                "path": "Projects/2_Cuddle_Cubbies/Media/1.png",
                "type": "image"
            },
            {
                "path": "https://drive.google.com/file/d/1l7Yr5Lh0oaazuou8Xloc6sex1MUry9RW/view?usp=sharing",
                "type": "image",
                "isExternal": true
            }
        ]
    },
    {
        "name": "Bent On Destruction",
        "description": "Fast-paced battles with fully destructible buildings simulation. Gather special attacks by filling up the destruction meter on each level and defeat the meanies by blasting their towers in strategic locations. Accumulate power-ups to customize the destruction. Developed by a structural engineer - these structures are flexible which means they will bend and twist before collapsing. The meanies will fire back, and you must act quickly!",
        "tech": [
            "Unity",
            "C#",
            "Unity DOTS/ECS",
            "ECS Physics",
            "Runtime Mesh Fracture",
            "Animations and UIs"
        ],
        "urls": [
            "https://store.steampowered.com/app/1691020/Bent_on_Destruction/"
        ],
        "role": [
            "Developed the game end-to-end.",
            "Programmed core game logic, enemy behaviors, and animations on Unity ECS.",
            "Designed and implemented UIs.",
            "Handled complete environment setup.",
            "Implemented and tuned high-performance ECS Physics for dynamic structural collapse."
        ],
        "media": [
            {
                "path": "Projects/3_Bent_On_Destruction/Media/1.jpg",
                "type": "image"
            },
            {
                "path": "https://drive.google.com/file/d/1ysLHZSXrfnQV4ZIGXQT_UZH6nP8FpdS_/view?usp=sharing",
                "type": "image",
                "isExternal": true
            },
            {
                "path": "https://drive.google.com/file/d/1fjzbA7H4O0AISFOorvmfsXq7-BwNLXNg/view?usp=sharing",
                "type": "image",
                "isExternal": true
            },
            {
                "path": "Projects/3_Bent_On_Destruction/Media/4.jpg",
                "type": "image"
            },
            {
                "path": "Projects/3_Bent_On_Destruction/Media/5.jpg",
                "type": "image"
            },
            {
                "path": "Projects/3_Bent_On_Destruction/Media/6.jpg",
                "type": "image"
            },
            {
                "path": "Projects/3_Bent_On_Destruction/Media/7.jpg",
                "type": "image"
            },
            {
                "path": "Projects/3_Bent_On_Destruction/Media/8.jpg",
                "type": "image"
            },
            {
                "path": "Projects/3_Bent_On_Destruction/Media/9.jpg",
                "type": "image"
            },
            {
                "path": "https://drive.google.com/file/d/1Gobhr3ES7ZQaI4WWB5fjpu9UGzAwXM13/view?usp=sharing",
                "type": "image",
                "isExternal": true
            }
        ]
    },
    {
        "name": "Great Library",
        "description": "Great Library is an engaging hybrid of puzzle-solving and card-battling mechanics. Players navigate through a series of interconnected rooms, solving intricate puzzles to unlock and collect powerful cards. These cards, each possessing unique abilities, are then strategically used in combat to defeat monsters and progress deeper into the dungeon.",
        "tech": [
            "Unity",
            "C#",
            "IAP"
        ],
        "urls": [],
        "role": [
            "Programmed the core turn-based battle logic, ensuring each card's unique abilities function seamlessly.",
            "Designed and implemented intuitive UI flows for navigation, card management, and combat scenarios.",
            "Developed the 2D player movement system for fluid room-to-room traversal.",
            "Handled the environment setup and level structuring to create immersive puzzle rooms."
        ],
        "media": [
            {
                "path": "Projects/4_Great_Library/Media/1.webp",
                "type": "image"
            },
            {
                "path": "https://drive.google.com/file/d/107z3n-ubrWfgi5yG_ggiVasBAYt5AHxu/view?usp=sharing",
                "type": "image",
                "isExternal": true
            }
        ]
    },
    {
        "name": "Hood Racing",
        "description": "Hood Racing is an innovative, geolocation-based drag racing game that combines the competitive mechanics of CSR Racing with the real-world exploration of Pok\u00e9mon Go. Players compete for dominance over real-world arenas, earning passive rewards until defeated by challengers.\n\nThe game features a deep economy where players purchase, rent, and manage geographically-tied garages to store their vehicles. Cars can be extensively customized\u2014from paint jobs and tires to nameplates and interiors\u2014and upgraded for peak performance. The experience also includes realistic vehicle maintenance mechanics and a unique 'Gallery' feature, rewarding players for visiting specific real-world locations to capture and share photos.",
        "tech": [
            "Unity",
            "C#",
            "Animations",
            "Animation Curve",
            "UI",
            "IAP",
            "Ads",
            "Mapbox"
        ],
        "urls": [],
        "role": [
            "Engineered drag race logic based on Animation Curves for smooth and predictable racing mechanics.",
            "Built Shader Graphs to enable comprehensive car customization (color, tires, nameplates, etc.).",
            "Architected the UI setup and implemented seamless UI flows across the entire game.",
            "Developed engaging in-game animations.",
            "Integrated third-party SDKs including Mapbox for geolocation, Ads, and In-App Purchases (IAP).",
            "Responsible for end-to-end Unity development for the complete game cycle.",
            "Designed the full environment layout and established the lighting setup."
        ],
        "media": [
            {
                "path": "Projects/5_Hood_Racing/Media/1.png",
                "type": "image"
            },
            {
                "path": "https://drive.google.com/file/d/1fJMreW7d30p_kx_YY6AtJRM2dqlSPamP/view?usp=drive_link",
                "type": "image",
                "isExternal": true
            }
        ]
    },
    {
        "name": "ECSDestructionToolkit",
        "description": "The Fracture ECS Toolkit is a powerful and modular destruction system built entirely on Unity\u2019s Entity Component System (ECS). Easily fracture 3D objects into dynamic chunks at runtime. Designed for performance and flexibility, it supports mesh and material customization, particle effects, prefab spawning, and post-fracture logic.\n\nPerfect for physics-based games, destructible environments, or procedural effects. Includes authoring components, runtime asset saving, and clean integration with Unity DOTS workflows.",
        "tech": [
            "NvBlast",
            "Unity",
            "C#",
            "Unity ECS",
            "Physics"
        ],
        "urls": [
            "https://assetstore.unity.com/packages/tools/physics/ecs-destruction-toolkit-326551"
        ],
        "role": [
            "Responsible for the end-to-end development of the package.",
            "Built a robust, market-ready Unity Asset Store package (not a standalone game), ensuring high code quality, documentation, and DOTS workflow integration.",
            "Managed the entire lifecycle of the Unity Asset Store package, including uploading, continuous updating, and documentation maintenance."
        ],
        "media": [
            {
                "path": "Projects/6_ECSDestructionToolkit/Media/1.webp",
                "type": "image"
            }
        ]
    },
    {
        "name": "CMS Video Recorder Suite",
        "description": "CMSVideoRecorderSuite is a high-performance, production-ready gameplay recording solution for Unity developers building Windows applications. Unlike other tools, it fully supports Mono and IL2CPP without relying on unstable child processes or bloated external dependencies. \n\nIt features true full-screen capture, specific camera renders, high-quality audio recording, and real-time encoding with pause/resume functionality. Optimized for multi-tasking and long sessions, it delivers export-ready outputs via a clean, developer-friendly API.",
        "tech": [
            "Unity",
            "C#",
            "C++",
            "C# Threading",
            "Texture Manipulation",
            "Audio and Video Encoding"
        ],
        "urls": [
            "https://assetstore.unity.com/packages/tools/video/cms-video-recorder-suite-windows-352082"
        ],
        "role": [
            "Responsible for the end-to-end development of the video recording suite.",
            "Engineered highly-optimized C# and C++ pipelines for real-time video and audio encoding without dropping frames.",
            "Managed the entire lifecycle of the Unity Asset Store package, including uploading, continuous updating, and documentation maintenance."
        ],
        "media": [
            {
                "path": "Projects/7_CMS_Video_Recorder_Suite/Media/1.webp",
                "type": "image"
            },
            {
                "path": "Projects/7_CMS_Video_Recorder_Suite/Media/2.webp",
                "type": "image"
            },
            {
                "path": "Projects/7_CMS_Video_Recorder_Suite/Media/3.webp",
                "type": "image"
            },
            {
                "path": "Projects/7_CMS_Video_Recorder_Suite/Media/4.webp",
                "type": "image"
            }
        ]
    },
    {
        "name": "Camera Screenshot Toolkit",
        "description": "The Camera Screenshot Toolkit is an essential, high-performance tool for Unity developers to capture customizable, high-quality screenshots directly from their projects. Fully compatible with Built-in, URP, and HDRP render pipelines, it offers seamless integration for capturing in-game content, promotional material, or VR/AR views. \n\nKey features include multiple output formats (PNG, JPG, EXR), customizable resolutions, and flexible saving to persistent data or custom paths. Supporting both asynchronous and synchronous captures with minimal performance impact, it\u2019s the perfect solution for game developers and studios needing robust screenshot functionality.",
        "tech": [
            "Unity",
            "C#",
            "Texture Manipulation"
        ],
        "urls": [
            "https://assetstore.unity.com/packages/tools/game-toolkits/camera-screenshot-toolkit-347056"
        ],
        "role": [
            "Designed and developed the Camera Screenshot Toolkit end-to-end for the Unity Asset Store.",
            "Implemented robust texture manipulation logic to capture high-quality screenshots seamlessly across Built-in, URP, and HDRP render pipelines.",
            "Managed the entire lifecycle of the Unity Asset Store package, including uploading, continuous updating, and documentation maintenance."
        ],
        "media": [
            {
                "path": "Projects/8_Camera_Screenshot_Toolkit/Media/1.webp",
                "type": "image"
            },
            {
                "path": "Projects/8_Camera_Screenshot_Toolkit/Media/2.webp",
                "type": "image"
            },
            {
                "path": "Projects/8_Camera_Screenshot_Toolkit/Media/3.webp",
                "type": "image"
            },
            {
                "path": "Projects/8_Camera_Screenshot_Toolkit/Media/4.webp",
                "type": "image"
            },
            {
                "path": "Projects/8_Camera_Screenshot_Toolkit/Media/5.webp",
                "type": "image"
            }
        ]
    },
    {
        "name": "SmartPrefs",
        "description": "SmartPref is a powerful and easy-to-use replacement for Unity\u2019s built-in PlayerPrefs. It adds versioning, namespacing (sections), caching, and JSON-based file saving so you can safely manage player data across updates, multiple save slots, and user profiles. \n\nStore any data type (custom classes, structs, lists) and separate data into sections. It features dual save modes (PlayerPrefs or JSON FileSystem), in-memory caching for performance, Base64 encoding for security, and seamless cross-platform compatibility. SmartPref gives you the flexibility of PlayerPrefs, the reliability of JSON, and the performance of caching\u2014all in one robust API.",
        "tech": [
            "Unity",
            "C#"
        ],
        "urls": [
            "https://assetstore.unity.com/packages/tools/utilities/smart-pref-330752"
        ],
        "role": [
            "Designed and developed the SmartPref utility end-to-end for the Unity Asset Store.",
            "Managed the entire lifecycle of the Unity Asset Store package, including uploading, continuous updating, and documentation maintenance."
        ],
        "media": [
            {
                "path": "Projects/9_SmartPrefs/Media/1.webp",
                "type": "image"
            },
            {
                "path": "Projects/9_SmartPrefs/Media/2.webp",
                "type": "image"
            },
            {
                "path": "Projects/9_SmartPrefs/Media/3.webp",
                "type": "image"
            },
            {
                "path": "Projects/9_SmartPrefs/Media/4.webp",
                "type": "image"
            },
            {
                "path": "Projects/9_SmartPrefs/Media/5.webp",
                "type": "image"
            },
            {
                "path": "Projects/9_SmartPrefs/Media/6.webp",
                "type": "image"
            },
            {
                "path": "Projects/9_SmartPrefs/Media/7.webp",
                "type": "image"
            }
        ]
    },
    {
        "name": "EZAPI",
        "description": "EzAPI is a Unity package that turns messy web requests into a clean, configurable API layer. Instead of scattering UnityWebRequest code and hard-coded URLs across your project, you define your endpoints once in an editor Settings window and access them via a type-safe EndPoints enum.\n\nYou configure base URLs, environments, and behaviors using APIConfig ScriptableObjects, then swap them per build without touching code. Each API call uses strongly-typed request and response classes. Under the hood, EzAPI provides request queuing, configurable max concurrent requests, retries, and structured error codes. The result is a robust, production-ready API system that lets you focus on gameplay instead of low-level networking details.",
        "tech": [
            "Unity",
            "C#",
            "Editor Scripting",
            "Web Requests"
        ],
        "urls": [
            "http://assetstore.unity.com/packages/tools/integration/ezapi-319708"
        ],
        "role": [
            "Responsible for the end-to-end development of the package.",
            "Managed the entire lifecycle of the Unity Asset Store package, including uploading, continuous updating, and documentation maintenance."
        ],
        "media": [
            {
                "path": "Projects/10_EZAPI/Media/1.webp",
                "type": "image"
            },
            {
                "path": "Projects/10_EZAPI/Media/2.webp",
                "type": "image"
            },
            {
                "path": "Projects/10_EZAPI/Media/3.webp",
                "type": "image"
            },
            {
                "path": "Projects/10_EZAPI/Media/4.webp",
                "type": "image"
            },
            {
                "path": "Projects/10_EZAPI/Media/5.webp",
                "type": "image"
            },
            {
                "path": "Projects/10_EZAPI/Media/6.webp",
                "type": "image"
            },
            {
                "path": "Projects/10_EZAPI/Media/7.webp",
                "type": "image"
            }
        ]
    },
    {
        "name": "RobbieSteal",
        "description": "Robbie Steal is a dynamic 2D platformer where players help Rob collect jewels across various worlds to solve mystery words. Each jewel uncovers a letter, adding a puzzle element to the traditional platforming action. Players navigate challenging levels by jumping, running, and crouching while dodging unique monsters\u2014each with specific behaviors and weak points, such as dinosaurs that are safe when walking or gorillas that need occasional rest. The action culminates at the end-of-level door, blending fast-paced platforming with strategic timing.",
        "tech": [
            "Unity",
            "C#",
            "Google and Apple SignIn",
            "IAP"
        ],
        "urls": [
            "https://play.google.com/store/apps/details?id=com.gamesbyadb.robbiesteal.android",
            "https://apps.apple.com/us/app/robbie-steal/id1594859479"
        ],
        "role": [
            "Handled critical bug fixes to ensure a seamless and polished gameplay experience.",
            "Integrated Apple Sign-In and Google Sign-In for frictionless user authentication.",
            "Architected robust data persistency systems to save player progress and puzzle states securely."
        ],
        "media": [
            {
                "path": "Projects/11_RobbieSteal/Media/1.jpeg",
                "type": "image"
            },
            {
                "path": "https://www.youtube.com/watch?v=ETXcB51h-UY",
                "type": "",
                "isExternal": true
            }
        ]
    }
];